version: '3.8'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8083:8081"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8-community
    ports:
      -"9000:9000"
    environment:
      SONARQUBE_USERNAME: admin
      SONARQUBE_PASSWORD: admin
    networks:
      - net
networks:
  net:
    name: networks_jenkins